spring:
  application:
    name: spring-cloud-zipkin
  cloud:
    consul:
      host: 127.0.0.1
      port: 8500
      discovery:
        healthCheckPath: /status
        healthCheckInterval: 5s
        health-check-critical-timeout: 3m
server:
  port: 9999