spring:
  application:
    name: spring-cloud-eureka
server:
  port: 7773
eureka:
  instance:
    hostname: eureka3
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: 'http://eureka1:7771/eureka/,http://eureka2:7772/eureka/'