spring:
  application:
    name: spring-cloud-statistic
  cloud:
    consul:
      host: 127.0.0.1
      port: 8500
      discovery:
        healthCheckPath: /status
        healthCheckInterval: 5s
server:
  port: 5001

