spring:
  application:
    name: spring-cloud-statistic
server:
  port: 5000
eureka:
  client:
    service-url:
      defaultZone: 'http://eureka1:7771/eureka/,http://eureka2:7772/eureka/,http://eureka3:7773/eureka/'